import type { Club, Condition } from "./types";

export const CLUBS: Club[] = [
  {
    id: 1,
    name: "TaylorMade Stealth 2 Driver",
    type: "Driver",
    brand: "TaylorMade",
    year: 2023,
    loft: "10.5°",
    shaft: "Fujikura Ventus Red 5 (Regular)",
    condition: "Very Good",
    price: 189,
    originalPrice: 549,
    photos: [
      "https://images.unsplash.com/photo-1535131749006-b7f58c99034b?w=800&q=85&fit=crop",
      "https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=800&q=85&fit=crop",
      "https://images.unsplash.com/photo-1592919505780-303950717480?w=800&q=85&fit=crop",
    ],
    specs: {
      headSize: "460cc",
      adjustable: true,
      forgiveness: "High",
      distance: "Very Long",
      spin: "Low-Mid",
      material: "60X Carbon Twist Face",
    },
    seller: "GolfPro_TX",
    rating: 4.8,
    reviews: 34,
    daysListed: 3,
    description:
      "The Stealth 2 Driver features TaylorMade's revolutionary 60X Carbon Twist Face — delivering explosive distance with a satisfying feel.",
  },
  {
    id: 2,
    name: "Callaway Paradym Irons (5-PW)",
    type: "Iron Set",
    brand: "Callaway",
    year: 2023,
    loft: "5–PW",
    shaft: "True Temper Elevate (Stiff)",
    condition: "Excellent",
    price: 449,
    originalPrice: 1299,
    photos: [
      "https://images.unsplash.com/photo-1593111774240-d529f12cf4bb?w=800&q=85&fit=crop",
      "https://images.unsplash.com/photo-1566735085-2f5b8a05e0d6?w=800&q=85&fit=crop",
      "https://images.unsplash.com/photo-1535131749006-b7f58c99034b?w=800&q=85&fit=crop",
    ],
    specs: {
      headSize: "N/A",
      adjustable: false,
      forgiveness: "High",
      distance: "Long",
      spin: "Mid",
      material: "AI-designed Forged Face Cup",
    },
    seller: "SunshineGolf",
    rating: 4.9,
    reviews: 61,
    daysListed: 7,
    description:
      "Callaway's most advanced iron ever. The AI-designed Forged Face Cup maximizes ball speed across the face — even on off-center hits.",
  },
  {
    id: 3,
    name: "Titleist Vokey SM9 Wedge 56°",
    type: "Wedge",
    brand: "Titleist",
    year: 2022,
    loft: "56°",
    shaft: "True Temper Dynamic Gold (Wedge Flex)",
    condition: "Good",
    price: 89,
    originalPrice: 179,
    photos: [
      "https://images.unsplash.com/photo-1592919505780-303950717480?w=800&q=85&fit=crop",
      "https://images.unsplash.com/photo-1561059488-916d69792237?w=800&q=85&fit=crop",
      "https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=800&q=85&fit=crop",
    ],
    specs: {
      headSize: "N/A",
      adjustable: false,
      forgiveness: "Mid",
      distance: "Short Game",
      spin: "Very High",
      material: "Tour Chrome Finish",
    },
    seller: "AceWedges",
    rating: 4.7,
    reviews: 89,
    daysListed: 12,
    description:
      "Precision milled grooves generate elite spin rates, while the progressive CG placement delivers unmatched feel and control around the greens.",
  },
  {
    id: 4,
    name: "Ping G430 Max Fairway 3-Wood",
    type: "Fairway Wood",
    brand: "Ping",
    year: 2023,
    loft: "15°",
    shaft: "Ping Tour 75 (Regular)",
    condition: "Like New",
    price: 159,
    originalPrice: 349,
    photos: [
      "https://images.unsplash.com/photo-1566735085-2f5b8a05e0d6?w=800&q=85&fit=crop",
      "https://images.unsplash.com/photo-1535131749006-b7f58c99034b?w=800&q=85&fit=crop",
      "https://images.unsplash.com/photo-1593111774240-d529f12cf4bb?w=800&q=85&fit=crop",
    ],
    specs: {
      headSize: "210cc",
      adjustable: true,
      forgiveness: "Very High",
      distance: "Long",
      spin: "Low",
      material: "Maraging Steel Face",
    },
    seller: "FairwayFred",
    rating: 4.6,
    reviews: 22,
    daysListed: 1,
    description:
      "Ping's most forgiving fairway wood ever, with a larger head profile and low CG for effortless launching from the fairway or tee.",
  },
  {
    id: 5,
    name: "Scotty Cameron Phantom X 5 Putter",
    type: "Putter",
    brand: "Titleist",
    year: 2022,
    loft: "3°",
    shaft: "Steel (35in)",
    condition: "Very Good",
    price: 249,
    originalPrice: 449,
    photos: [
      "https://images.unsplash.com/photo-1561059488-916d69792237?w=800&q=85&fit=crop",
      "https://images.unsplash.com/photo-1592919505780-303950717480?w=800&q=85&fit=crop",
      "https://images.unsplash.com/photo-1566735085-2f5b8a05e0d6?w=800&q=85&fit=crop",
    ],
    specs: {
      headSize: "Mallet",
      adjustable: false,
      forgiveness: "Very High",
      distance: "N/A",
      spin: "N/A",
      material: "304 Stainless Steel",
    },
    seller: "PuttMaster",
    rating: 5.0,
    reviews: 47,
    daysListed: 5,
    description:
      "High-MOI mallet putter crafted from 304 stainless steel with a plumber's neck hosel and face-balanced design. Beloved on Tour.",
  },
  {
    id: 6,
    name: "Cleveland Launcher XL Halo Hybrid 4H",
    type: "Hybrid",
    brand: "Cleveland",
    year: 2022,
    loft: "22°",
    shaft: "Action Ultralite 45 (Regular)",
    condition: "Good",
    price: 69,
    originalPrice: 199,
    photos: [
      "https://images.unsplash.com/photo-1587174486073-ae5e5cff23aa?w=800&q=85&fit=crop",
      "https://images.unsplash.com/photo-1593111774240-d529f12cf4bb?w=800&q=85&fit=crop",
      "https://images.unsplash.com/photo-1561059488-916d69792237?w=800&q=85&fit=crop",
    ],
    specs: {
      headSize: "N/A",
      adjustable: false,
      forgiveness: "Very High",
      distance: "Long",
      spin: "Mid-High",
      material: "HiBore Crown",
    },
    seller: "HybridHero",
    rating: 4.5,
    reviews: 18,
    daysListed: 14,
    description:
      "Cleveland's most forgiving hybrid. The HiBore Crown shifts CG low and deep for effortless launch. MainFrame face boosts ball speed.",
  },
];

export const conditionColor: Record<Condition, string> = {
  "Like New": "#22c55e",
  Excellent: "#84cc16",
  "Very Good": "#eab308",
  Good: "#f97316",
  Fair: "#ef4444",
};

export const conditionBadgeBg: Record<Condition, string> = {
  "Like New": "#f0fdf4",
  Excellent: "#f7fee7",
  "Very Good": "#fefce8",
  Good: "#fff7ed",
  Fair: "#fef2f2",
};

export const CLUB_TYPES = [
  "Driver",
  "Iron Set",
  "Fairway Wood",
  "Hybrid",
  "Wedge",
  "Putter",
  "Iron (Single)",
  "Utility Iron",
];

export const CONDITIONS: Condition[] = [
  "Like New",
  "Excellent",
  "Very Good",
  "Good",
  "Fair",
];
