import type { Club, Condition } from "./types";
import { clubIconFor } from "./clubIcons";

export const CLUBS: Club[] = [
  {
    id: 1,
    name: "TaylorMade Stealth 2 Driver",
    type: "Driver",
    brand: "TaylorMade",
    year: 2023,
    loft: "10.5°",
    shaft: "Fujikura Ventus Red 5 (Regular)",
    condition: "Very Good",
    price: 189,
    originalPrice: 549,
    photos: [clubIconFor("Driver")],
    specs: {
      headSize: "460cc",
      adjustable: true,
      forgiveness: "High",
      distance: "Very Long",
      spin: "Low-Mid",
      material: "60X Carbon Twist Face",
    },
    seller: "GolfPro_TX",
    rating: 4.8,
    reviews: 34,
    daysListed: 3,
    description:
      "The Stealth 2 Driver features TaylorMade's revolutionary 60X Carbon Twist Face — delivering explosive distance with a satisfying feel.",
  },
  {
    id: 2,
    name: "Callaway Paradym Irons (5-PW)",
    type: "Iron Set",
    brand: "Callaway",
    year: 2023,
    loft: "5–PW",
    shaft: "True Temper Elevate (Stiff)",
    condition: "Excellent",
    price: 449,
    originalPrice: 1299,
    photos: [clubIconFor("Iron Set")],
    specs: {
      headSize: "N/A",
      adjustable: false,
      forgiveness: "High",
      distance: "Long",
      spin: "Mid",
      material: "AI-designed Forged Face Cup",
    },
    seller: "SunshineGolf",
    rating: 4.9,
    reviews: 61,
    daysListed: 7,
    description:
      "Callaway's most advanced iron ever. The AI-designed Forged Face Cup maximizes ball speed across the face — even on off-center hits.",
  },
  {
    id: 3,
    name: "Titleist Vokey SM9 Wedge 56°",
    type: "Wedge",
    brand: "Titleist",
    year: 2022,
    loft: "56°",
    shaft: "True Temper Dynamic Gold (Wedge Flex)",
    condition: "Good",
    price: 89,
    originalPrice: 179,
    photos: [clubIconFor("Wedge")],
    specs: {
      headSize: "N/A",
      adjustable: false,
      forgiveness: "Mid",
      distance: "Short Game",
      spin: "Very High",
      material: "Tour Chrome Finish",
    },
    seller: "AceWedges",
    rating: 4.7,
    reviews: 89,
    daysListed: 12,
    description:
      "Precision milled grooves generate elite spin rates, while the progressive CG placement delivers unmatched feel and control around the greens.",
  },
  {
    id: 4,
    name: "Ping G430 Max Fairway 3-Wood",
    type: "Fairway Wood",
    brand: "Ping",
    year: 2023,
    loft: "15°",
    shaft: "Ping Tour 75 (Regular)",
    condition: "Like New",
    price: 159,
    originalPrice: 349,
    photos: [clubIconFor("Fairway Wood")],
    specs: {
      headSize: "210cc",
      adjustable: true,
      forgiveness: "Very High",
      distance: "Long",
      spin: "Low",
      material: "Maraging Steel Face",
    },
    seller: "FairwayFred",
    rating: 4.6,
    reviews: 22,
    daysListed: 1,
    description:
      "Ping's most forgiving fairway wood ever, with a larger head profile and low CG for effortless launching from the fairway or tee.",
  },
  {
    id: 5,
    name: "Scotty Cameron Phantom X 5 Putter",
    type: "Putter",
    brand: "Titleist",
    year: 2022,
    loft: "3°",
    shaft: "Steel (35in)",
    condition: "Very Good",
    price: 249,
    originalPrice: 449,
    photos: [clubIconFor("Putter")],
    specs: {
      headSize: "Mallet",
      adjustable: false,
      forgiveness: "Very High",
      distance: "N/A",
      spin: "N/A",
      material: "304 Stainless Steel",
    },
    seller: "PuttMaster",
    rating: 5.0,
    reviews: 47,
    daysListed: 5,
    description:
      "High-MOI mallet putter crafted from 304 stainless steel with a plumber's neck hosel and face-balanced design. Beloved on Tour.",
  },
  {
    id: 6,
    name: "Cleveland Launcher XL Halo Hybrid 4H",
    type: "Hybrid",
    brand: "Cleveland",
    year: 2022,
    loft: "22°",
    shaft: "Action Ultralite 45 (Regular)",
    condition: "Good",
    price: 69,
    originalPrice: 199,
    photos: [clubIconFor("Hybrid")],
    specs: {
      headSize: "N/A",
      adjustable: false,
      forgiveness: "Very High",
      distance: "Long",
      spin: "Mid-High",
      material: "HiBore Crown",
    },
    seller: "HybridHero",
    rating: 4.5,
    reviews: 18,
    daysListed: 14,
    description:
      "Cleveland's most forgiving hybrid. The HiBore Crown shifts CG low and deep for effortless launch. MainFrame face boosts ball speed.",
  },
  {
    id: 7,
    name: "Cobra Darkspeed Driver",
    type: "Driver",
    brand: "Cobra",
    year: 2024,
    loft: "10.5°",
    shaft: "KBS TD 65 (Regular)",
    condition: "Excellent",
    price: 279,
    originalPrice: 599,
    photos: [clubIconFor("Driver")],
    specs: {
      headSize: "460cc",
      adjustable: true,
      forgiveness: "High",
      distance: "Very Long",
      spin: "Low",
      material: "PWR-Bridge Titanium Face",
    },
    seller: "CobraFan88",
    rating: 4.6,
    reviews: 15,
    daysListed: 4,
    description:
      "Cobra's fastest driver yet, with a PWR-Bridge weighting system that shifts CG for a locked-in, low-spin flight.",
  },
  {
    id: 8,
    name: "Mizuno JPX923 Hot Metal Irons (5-PW)",
    type: "Iron Set",
    brand: "Mizuno",
    year: 2022,
    loft: "5–PW",
    shaft: "Nippon NS Pro 950 (Regular)",
    condition: "Good",
    price: 349,
    originalPrice: 899,
    photos: [clubIconFor("Iron Set")],
    specs: {
      headSize: "N/A",
      adjustable: false,
      forgiveness: "Very High",
      distance: "Long",
      spin: "Mid",
      material: "Nickel Chromoly Face",
    },
    seller: "MizunoMaster",
    rating: 4.8,
    reviews: 27,
    daysListed: 9,
    description:
      "A game-improvement iron with a thin, fast face and Mizuno's signature soft feel — forgiving without sacrificing workability.",
  },
  {
    id: 9,
    name: "Wilson Staff Model CB Wedge 52°",
    type: "Wedge",
    brand: "Wilson",
    year: 2023,
    loft: "52°",
    shaft: "True Temper Dynamic Gold (Wedge Flex)",
    condition: "Very Good",
    price: 79,
    originalPrice: 159,
    photos: [clubIconFor("Wedge")],
    specs: {
      headSize: "N/A",
      adjustable: false,
      forgiveness: "Mid",
      distance: "Short Game",
      spin: "High",
      material: "Grain Flow Forged Steel",
    },
    seller: "WilsonWedgeGuy",
    rating: 4.5,
    reviews: 11,
    daysListed: 6,
    description:
      "A tour-inspired forged wedge with a compact head shape and precision grooves for reliable spin around the greens.",
  },
  {
    id: 10,
    name: "Srixon ZX5 Mk II Fairway Wood",
    type: "Fairway Wood",
    brand: "Srixon",
    year: 2023,
    loft: "16.5°",
    shaft: "Mitsubishi Tensei AV Blue (Regular)",
    condition: "Good",
    price: 129,
    originalPrice: 279,
    photos: [clubIconFor("Fairway Wood")],
    specs: {
      headSize: "180cc",
      adjustable: true,
      forgiveness: "High",
      distance: "Long",
      spin: "Mid",
      material: "Rebound Frame Face",
    },
    seller: "SrixonSteve",
    rating: 4.4,
    reviews: 9,
    daysListed: 11,
    description:
      "A compact, tour-shaped fairway wood with a Rebound Frame face for consistent ball speed and easy workability.",
  },
  {
    id: 11,
    name: "PXG 0317X Hybrid",
    type: "Hybrid",
    brand: "PXG",
    year: 2023,
    loft: "21°",
    shaft: "PX HZRDUS Smoke (Regular)",
    condition: "Excellent",
    price: 189,
    originalPrice: 349,
    photos: [clubIconFor("Hybrid")],
    specs: {
      headSize: "N/A",
      adjustable: true,
      forgiveness: "High",
      distance: "Long",
      spin: "Mid",
      material: "HT1770 Steel Face",
    },
    seller: "PXG_Perfection",
    rating: 4.7,
    reviews: 13,
    daysListed: 2,
    description:
      "A precision-milled hybrid with adjustable weighting, built to fill the gap between your longest iron and fairway wood.",
  },
  {
    id: 12,
    name: "Bettinardi Studio Stock 28 Putter",
    type: "Putter",
    brand: "Bettinardi",
    year: 2022,
    loft: "3.5°",
    shaft: "Steel (34in)",
    condition: "Very Good",
    price: 299,
    originalPrice: 495,
    photos: [clubIconFor("Putter")],
    specs: {
      headSize: "Blade",
      adjustable: false,
      forgiveness: "Mid",
      distance: "N/A",
      spin: "N/A",
      material: "Carbon Steel, Honeycomb Face Milling",
    },
    seller: "BettinardiCollector",
    rating: 4.9,
    reviews: 21,
    daysListed: 7,
    description:
      "A precision-milled blade putter with Bettinardi's honeycomb face milling for soft feel and consistent roll off the face.",
  },
];

export const conditionColor: Record<Condition, string> = {
  "Like New": "#22c55e",
  Excellent: "#84cc16",
  "Very Good": "#eab308",
  Good: "#f97316",
  Fair: "#ef4444",
};

export const conditionBadgeBg: Record<Condition, string> = {
  "Like New": "#f0fdf4",
  Excellent: "#f7fee7",
  "Very Good": "#fefce8",
  Good: "#fff7ed",
  Fair: "#fef2f2",
};

export const CLUB_TYPES = [
  "Driver",
  "Iron Set",
  "Fairway Wood",
  "Hybrid",
  "Wedge",
  "Putter",
  "Iron (Single)",
  "Utility Iron",
];

export const CONDITIONS: Condition[] = [
  "Like New",
  "Excellent",
  "Very Good",
  "Good",
  "Fair",
];
